service: hoagietools-service

plugins:
  - serverless-api-cloudfront
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
frameworkVersion: '2'

custom:
  myStage: ${opt:stage, self:provider.stage}
  apiCloudFront:
    domain: hoagietools-svc.hoagieman.net
    certificate: arn:aws:acm:us-east-1:796987500533:certificate/34ddd63f-ae46-4812-a2ee-39b9594d8ef2
    compress: true
    # Unfortunately, the DefaultTTL must be set manually

provider:
  name: aws
  runtime: nodejs12.x
  httpApi:
    cors: true
#  iamRoleStatements:
#    - Effect: 'Allow'
#      Action:
#        - 'dynamodb:Query'
#        - 'dynamodb:Scan'
#        - 'dynamodb:GetItem'
#        - 'dynamodb:PutItem'
#        - 'dynamodb:UpdateItem'
#        - 'dynamodb:DeleteItem'
#      Resource:
#        Fn::GetAtt:
#          - StreamerMusicQueueTable
#          - Arn
  environment:
    PERSPECTIVE_API_KEY: ${file(secrets.yml):perspectiveApiKey}

functions:
  chatevalget:
    handler: chatevalHandler.eval
    events:
      - http:
          method: GET
          path: /api/chateval
          cors: true
    environment:
      STAGE: ${self:custom.myStage}

  chatevalpost:
    handler: chatevalHandler.eval
    events:
      - http:
          method: POST
          path: /api/chateval
          cors: true
    environment:
      STAGE: ${self:custom.myStage}

#    StreamerMusicQueueTable:
#      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Retain
#      Properties:
#        AttributeDefinitions:
#          - AttributeName: CategoryKey
#            AttributeType: S
#          - AttributeName: SubKey
#            AttributeType: S
#        KeySchema:
#          - AttributeName: CategoryKey
#            KeyType: HASH
#          - AttributeName: SubKey
#            KeyType: RANGE
#        ProvisionedThroughput:
#          ReadCapacityUnits: 1
#          WriteCapacityUnits: 1
#        TableName: ${self:custom.myTableName}