service: song-eval-service

useDotenv: true
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-log-retention

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true
    authorizers:
      twitchAuthenticator:
        type: request
        functionArn: arn:aws:lambda:us-east-1:796987500533:function:hoagietools-service-prod-twitchAuthenticator
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: "*"

custom:
  prune:
    automatic: false
    number: 1
  myStage: ${opt:stage, 'dev'}
  #myTableName: HoagieTools-${opt:stage, self:provider.stage}
  myTableName: HoagieTools-prod
  domainName:
    development: songeval-dev.hoagieman.net
    prod: songeval.hoagieman.net

functions:
  test:
    handler: handlers.test
    events:
      - httpApi:
          method: GET
          path: /v1/test
          authorizer: twitchAuthenticator
    environment:
      STAGE: ${self:custom.myStage}
      TABLENAME: ${self:custom.myTableName}

resources: ${file(../../libs/api-util/src/lib/serverless/serviceCloudfront.yml):resources}
