service: dono-service

useDotenv: true
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-log-retention

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true
    authorizers:
      twitchAuthorizer:
        functionName: twitchAuthorizer
        type: request
        enableSimpleResponses: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: "*"
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: arn:aws:events:*:796987500533:event-bus/default
    - Effect: Allow
      Action:
        - 'ecs:DescribeServices'
      Resource: '*'
  logRetentionInDays: 30 # used to set a global value for all functions

custom:
  prune:
    automatic: false
    number: 1
  myStage: ${opt:stage, 'development'}
  myTableName: HoagieTools-${opt:stage, self:provider.stage}
  domainName:
    development: dono-dev.hoagieman.net
    prod: dono.hoagieman.net

functions:
  twitchAuthorizer:
    handler: handlers.authorizer
    environment:
      STAGE: ${self:custom.myStage}
      TABLENAME: ${self:custom.myTableName}

  getdono:
    handler: handlers.getdono
    events:
      - httpApi:
          method: GET
          path: /api/v1/{streamerId}
          authorizer: twitchAuthorizer
    environment:
      STAGE: ${self:custom.myStage}
      TABLENAME: ${self:custom.myTableName}

  twitchchatevents:
    handler: handlers.twitchchatevents
    events:
      - eventBridge:
          pattern:
            source:
              - 'hoagie.twitch-chat'
    environment:
      STAGE: ${self:custom.myStage}
      TABLENAME: ${self:custom.myTableName}

resources: ${file(../../libs/api-util/src/lib/serverless/serviceCloudfront.yml):resources}
